Rename plugin
opensearch-project/job-scheduler pull request #14
Opened 2021-04-24 00:31 UTC by qreshi

Signed-off-by: Mohammad Qureshi <qreshi@amazon.com>

### Description

Updating plugin name to contain `opensearch`
 
### Check List
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-04-24 00:47 UTC, lezzago approved these changes

2021-04-24 20:45 UTC, dblock requested changes

2021-04-24 20:45 UTC, dblock commented on build.gradle
> +    version = "${opendistroVersion}.0-beta1"
Let's get rid of these `opendistroVersion` while we're at it?

2021-04-24 20:45 UTC, dblock commented on build.gradle
>      description 'Open Distro for Elasticsearch job schduler plugin'
Let's fix the description to be OpenSearch, including the `schduler` typo?

2021-04-25 22:36 UTC, qreshi commented
@dblock Addressed the comments.

I also had a couple questions.

1. What should we update this to in `build.gradle`?:
https://github.com/opensearch-project/job-scheduler/blob/0918a568d215d2b448cd21fcd350f20d38a1c7ed/build.gradle#L140-L146

2. Previously ODFE (OpenDistro for Elasticsearch) used to refer to the distribution whereas Elasticsearch referred to the backend search engine. Now, OpenSearch refers to both the distribution and the backend search engine. Do you think this could get confusing at all when referencing distribution versions/engine versions and the like?

2021-04-26 16:07 UTC, dblock approved these changes

2021-04-26 16:09 UTC, dblock commented
> @dblock Addressed the comments.
> 
> I also had a couple questions.
> 
> 1. What should we update this to in `build.gradle`?:
>    https://github.com/opensearch-project/job-scheduler/blob/0918a568d215d2b448cd21fcd350f20d38a1c7ed/build.gradle#L140-L146
> 2. Previously ODFE (OpenDistro for Elasticsearch) used to refer to the distribution whereas Elasticsearch referred to the backend search engine. Now, OpenSearch refers to both the distribution and the backend search engine. Do you think this could get confusing at all when referencing distribution versions/engine versions and the like?

I'd be guessing on both. I think we should standardize this soon,  /cc:@saratvemulapalli

2021-04-26 16:09 UTC, merged

2021-04-26 16:17 UTC, saratvemulapalli commented
> > @dblock Addressed the comments.
> > I also had a couple questions.
> > 
> > 1. What should we update this to in `build.gradle`?:
> >    https://github.com/opensearch-project/job-scheduler/blob/0918a568d215d2b448cd21fcd350f20d38a1c7ed/build.gradle#L140-L146
> > 2. Previously ODFE (OpenDistro for Elasticsearch) used to refer to the distribution whereas Elasticsearch referred to the backend search engine. Now, OpenSearch refers to both the distribution and the backend search engine. Do you think this could get confusing at all when referencing distribution versions/engine versions and the like?
> 
> I'd be guessing on both. I think we should standardize this soon, /cc:@saratvemulapalli

Yeah definitely a great question. There are multiple questions involved, which are open:

1. Url for downloads
2. Docs URL
3. Distinguishing between backend engine version and plugin version.